print("*******table of 8*******")
print("8*1")
print("8*2")
print("8*3")
print("8*4")
print("8*5")
print("8*6")
print("8*7")
print("8*8")
print("8*9")
print("8*10")
print("*******PRINTING YOUR ADDRESS*******")
print("Powai Police Station")
print("DP Rd Number 9,")
print("Rambaug, Chandivali,")
print("Powai, Mumbai, Maharashtra 400076")
def tbl(x):
    for i in range(1,11):
              print(x*i)
tbl(5)
            
