marks=[]
a=int(input("Enter Marks:"))
marks.append(a)
a=int(input("Enter Marks:"))
marks.append(a)
a=int(input("Enter Marks:"))
marks.append(a)
a=int(input("Enter Marks:"))
marks.append(a)
a=int(input("Enter Marks:"))
marks.append(a)
a=int(input("Enter Marks:"))
marks.append(a)
a=int(input("Enter Marks:"))
marks.append(a)
a=int(input("Enter Marks:"))
marks.append(a)
a=int(input("Enter Marks:"))
marks.append(a)
a=int(input("Enter Marks:"))
marks.append(a)
print(marks)
a=marks.count(100)
print('Number Of student Obtained Marks 100 is:',a)
print('*********SUM OF SINGLE DIGIT PRIME NUMBER *********')
prime=[2,3,5,7]
print("Sum of Single digit Prime Numbe:",(prime[0]+prime[1]+
prime[2]+prime[3]))